name: Dockerhub deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  IMAGE_NAME: siluanaklein/${{ github.repository }}

jobs:
  build-test-application:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # baixa o código do repo na máquina, faz o git checkout
      - uses: actions/setup-node@v4
        with:
          node-version: 17.9.1
      - run: npm ci
      - run: npm run test

  build-and-push-docker-image:
    name: Build and push docker image to dockerhub # https://github.com/marketplace/actions/build-and-push-docker-images
    needs: build-test-application
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images:${{ env.IMAGE_NAME }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
